# Generated by Django 4.1.5 on 2023-02-06 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 2, 6, 18, 1, 24, 739054, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
